export const TEMPLATE_CONFIGS = [
  {
    id: 'newyear' as const,
    name: 'New Year Postcard',
    nameCN: '新年明信片',
    icon: '🎊',
    description: 'Vintage New Year postcard with handwritten style',
    descriptionCN: '复古新年明信片，支持手写体文字',
  },
  {
    id: 'postcard' as const,
    name: 'Film Postcard',
    nameCN: '胶片明信片',
    icon: '📮',
    description: 'Create vintage film-style postcards',
    descriptionCN: '创作复古胶片风格明信片',
  },
  {
    id: 'bookmark' as const,
    name: 'Artistic Bookmark',
    nameCN: '艺术书签',
    icon: '🔖',
    description: 'Design elegant bookmarks',
    descriptionCN: '设计优雅的艺术书签',
  },
  {
    id: 'polaroid' as const,
    name: 'Polaroid Frame',
    nameCN: '拍立得相框',
    icon: '📸',
    description: 'Classic instant photo style',
    descriptionCN: '经典即时成像风格',
  },
  {
    id: 'greeting' as const,
    name: 'Greeting Card',
    nameCN: '祝福贺卡',
    icon: '💌',
    description: 'Elegant greeting card for special occasions',
    descriptionCN: '精致祝福贺卡，适合各种场合',
  },
  {
    id: 'businesscard' as const,
    name: 'Business Card',
    nameCN: '摄影师名片',
    icon: '👤',
    description: 'Professional photographer business card',
    descriptionCN: '专业摄影师个人名片',
  },
];
